version: 2

jobs:
  build:
    docker:
      - image: tprk77/ttfrmci
    steps:
      - checkout
      - run:
          name: Build tests and utilities
          command: |
            make BUILD_GRAPHICS=false
      - run:
          name: Run the tests
          command: |
            make test
  coverage:
    docker:
      - image: tprk77/ttfrmci
    steps:
      - checkout
      - run:
          name: Build and run tests for coverage
          command: |
            make coverage
      - run:
          name: Generate and upload coverage
          command: |
            cpp-coveralls -r . -b build_cov -i ttfrm

workflows:
  version: 2
  build_and_coverage:
    jobs:
      - build
      - coverage:
          requires:
            - build
